# Generated by Django 5.1.5 on 2025-01-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_quizsession_aborted_at_alter_quizsession_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsession',
            old_name='id',
            new_name='session_id',
        ),
    ]
